[package]
name = "example_wallet_bdk_tx"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
bdk_wallet = { path = "../../wallet", features = ["file_store"] }
bdk_esplora = { version = "0.20", features = ["blocking"] }

anyhow = "1"
