[package]
name = "example_wallet_electrum"
version = "0.2.0"
edition = "2021"

[dependencies]
bdk_wallet = { version = "2.1.0", features = ["rusqlite"] }
bdk_electrum = { version = "0.23.1" }
anyhow = "1"
