[package]
name = "example_wallet_electrum"
version = "0.2.0"
edition = "2021"

[dependencies]
bdk_wallet = { path = "../../wallet", features = ["file_store"] }
#bdk_electrum = { version = "0.21" }
bdk_electrum = { git = "https://github.com/evanlinjin/bdk", branch = "superimposed_canonicalization" }
anyhow = "1"
