[package]
name = "example_wallet_rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk_wallet = { path = "../../wallet", features = ["rusqlite"] }
bdk_bitcoind_rpc = { version = "0.21.0", path = "../../../bdk/crates/bitcoind_rpc" }

anyhow = "1"
clap = { version = "4.5.17", features = ["derive", "env"] }
ctrlc = "3.4.6"
