name: Weekly cargo-mutants

permissions: {}

on:
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00
  workflow_dispatch: # allows manual triggering

jobs:
  cargo-mutants:
    name: Cargo Mutants
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@2383334cf567d78771fc7d89b6b3802ef1412cf6
        with:
          tool: cargo-mutants
      - run: cargo mutants --in-place --no-shuffle
      - uses: actions/upload-artifact@v4
        with:
          name: mutants.out
          path: mutants.out
      - name: Check for new mutants
        if: always()
        run: |
          if [ -s mutants.out/missed.txt ]; then
            echo "New missed mutants found"
            MUTANTS_VERSION=$(cargo mutants --version)
            gh issue create \
            --title "cargo-mutants: new mutants found" \
            --body "$(cat <<EOF
          Displaying up to the first 10 mutants:
          \`\`\`
          $(head -n 10 mutants.out/missed.txt)
          \`\`\`
          Running cargo mutants version: ${MUTANTS_VERSION}
          For the complete list, please check the [mutants.out artifact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          EOF
          )"
            echo "create_issue=true" >> $GITHUB_ENV
          else
            echo "No new mutants found"
            echo "create_issue=false" >> $GITHUB_ENV
          fi
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
