name: Zizmor Actions Analysis

# Analyzes GitHub Actions workflows for security vulnerabilities using zizmor.
# Runs on pushes to master and all pull requests to detect potential security issues
# in workflow configurations. Results are uploaded to GitHub's security dashboard.
# The .github/zizmor.yml file configures the rules this action will check against.

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["**"]

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Rust Cache
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1

      - name: Install zizmor
        run: cargo install zizmor --locked --version 1.6.0

      - name: Run zizmor 🌈
        run: zizmor --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: zizmor